const InvitationsActionTypes = {
  GET_INVITATIONS: "GET_INVITATIONS",
  GET_INVITATIONS_FAILURE: "GET_INVITATIONS_FAILURE",
  GET_INVITATIONS_SUCCESS: "GET_INVITATIONS_SUCCESS",
  NEW_INVITATION: "NEW_INVITATION",
  NEW_INVITATION_SUCCESS: "NEW_INVITATION_SUCCESS",
  NEW_INVITATION_FAILURE: "NEW_INVITATION_FAILURE",
};
export default InvitationsActionTypes;
