const GiftsActionTypes = {
  GET_GIFTS: "GET_GIFTS",
  EDIT_GIFT: "EDIT_GIFT",
  GET_GIFTS_FAILURE: "GET_GIFTS_FAILURE",
  GET_GIFTS_SUCCESS: "GET_GIFTS_SUCCESS",
  GET_IMAGES: "GET_IMAGES",
  GET_IMAGES_SUCCESS: "GET_IMAGES_SUCCESS",
  GET_IMAGES_FAILURE: "GET_IMAGES_FAILURE",
  NEW_GIFT: "NEW_GIFT",
  NEW_GIFT_SUCCESS: "NEW_GIFT_SUCCESS",
  NEW_GIFT_FAILURE: "NEW_GIFT_FAILURE",
};
export default GiftsActionTypes;
